

export const ADD_DATA_FAILURE = "ADD_DATA_FAILURE"
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS"
export const ADD_DATA_REQUEST = "ADD_DATA_REQUEST"

export const GET_CART_DATA_FAILURE = "GET_CART_DATA_FAILURE"
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS"
export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST"